export const MOVIE = {
  GET_MOVIES: 'GET_MOVIES',
  GET_MOVIE: 'GET_MOVIE',
  CHANGE_SORT_BY: 'CHANGE_SORT_BY',
  CHANGE_SEARCH_BY: 'CHANGE_SEARCH_BY',
  CHANGE_SEARCH: 'CHANGE_SEARCH',
  MOVIES_RECEIVED: 'MOVIES_RECEIVED',
  MOVIE_RECEIVED: 'MOVIE_RECEIVED',
  RESET_MOVIE: 'RESET_MOVIE',
  RESET_SEARCH: 'RESET_SEARCH',
};
